### ISSUE TITLE
different line endings on windows and linux

### ISSUE THREAD

**Issue by heapifyman** [mojohaus/license-maven-plugin#56]
We have a problem with the license-plugin messing up line endings when adding the license header to source files in a mixed windows / unix environment using git for version control.

License information uses unix line endings and comes from a dependency artifact using  `<licenseResolver>classpath:`.

I also have configured `<canUpdateCopyright>true</canUpdateCopyright>` and `<canUpdateDescription>true</canUpdateDescription>`.

Git is configured on Linux machines with `core.autocrlf=input` on Windows with `core.autocrlf=true`, thus sources are committed with Unix line endings and converted to Windows line endings when cloning to a Windows machine - as recommended.

Now, when the license-plugin's update-file-header is run on a windows machine and the source file already has a license header, the license header will be replaced - in fact, only the line endings will be changed from windows style to unix style.
That in turn lets git think the file has been changed, which leads to the situation, where git and our IDE show every source file with a header as changed, although you haven't actually changed the code.
As you can imagine, that makes it quite hard to work with git because you can't really see what actual changes will be included in a commit.

Is there a way we can change this behaviour? Have we maybe misconfigured the plugin?
As a workaround we now have disabled the license-plugin on windows machines via maven profile but that's hardly an ideal solution.

Any hints would be appreciated.
Thanks in advance.

P.S.: I have used the command described at http://stackoverflow.com/questions/121392/how-to-determine-the-line-ending-of-a-file/2065154#2065154 to determine the line endings.

**Comment by mpkorstanje** [comment]
Looks like the line endings are read directly from the license files. Additionally a few line endings \n are added when strings are concatenated.

**Comment by heapifyman** [comment]
Wow, that was fast.
One question though, shouldn't the "\n" used in the different FileHeaderTransformers also be replaced?

**Comment by mpkorstanje** [comment]
The buffered reader effectively splits the string on `(\r)|(\n)|(\r\n)` which covers old-mac, unix and windows respectively. The way line endings are added no longer matters.

Should be noted that this changes all the line endings in the file to be platform appropriate, not just those in the header as the plugin has done before. I don't see any problems with that though.

**Comment by mpkorstanje** [comment]
Looks like I'm tripping up some tests though. :S

**Comment by mpkorstanje** [comment]
Also worth noting that the groovy integration tests are now platform specific. Not so groovy.

**Comment by mpkorstanje** [comment]
Fixed those too. 

@tchemit Everything should be good to go now.

**Comment by heapifyman** [comment]
@mpkorstanje thanks. With your changes `update-file-header` run on a windows machine produces correct line endings and git does not get "confused" anymore.

**Comment by heapifyman** [comment]
since changes in https://github.com/mojohaus/license-maven-plugin/pull/57 resolve the issue, what is the usual time frame for PRs to be included in an official release?

**Comment by tchemit** [comment]
Ok, PR#57 was merged. I close this issue, a release should be started next week :).

**Comment by heapifyman** [comment]
It seems that I was wrong, PR #57 does not fully fix the issue.

I created a new PR #67 with some additional changes. Without those changes the line endings are still changed and git marks every source file as changed, at least in my case.
